// Core data structures from final_spec.md Section 4

// User and Profile types
export interface Profile {
  id: string;
  user_id: string;
  child_name: string;
  parent_name: string | null;
  birthdate: string; // ISO date string
  created_at: string;
  updated_at: string;
}

export interface User {
  id: string;
  email: string;
  profile?: Profile;
}

// Utility function to calculate age from birthdate
export function calculateAge(birthdate: string): number {
  const today = new Date();
  const birthDate = new Date(birthdate);
  let age = today.getFullYear() - birthDate.getFullYear();
  const monthDiff = today.getMonth() - birthDate.getMonth();

  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }

  return age;
}

export interface Problem {
  id: string;
  source_book: string;
  class: number;
  chapter: number;
  problem_number: number;
  text: string;
  expected_answer: string;
  requires_multi_step?: boolean;
  complexity?: 'easy' | 'medium' | 'hard';
}

export interface Message {
  role: 'student' | 'tutor';
  text: string;
  timestamp: string;
  badge_type?: 'partial_progress' | 'hint_given' | 'corrective_feedback';
}

export interface Session {
  session_id: string;
  student_name: string;
  created_at: string;
  completed_at?: string;
  problem_attempts: ProblemAttempt[];
}

export interface ProblemAttempt {
  attempt_id?: string; // UUID generated by database
  session_id?: string; // UUID reference
  problem_id: string;
  started_at: string;
  completed_at?: string;
  messages?: Message[]; // Not stored in DB, joined when needed
  hints_used: number;
  final_status?: 'mastered' | 'incomplete' | 'struggling';
  mastery_check_passed?: boolean;
  is_mastery_check?: boolean;
  original_problem_id?: string;
}

// LLM API types

export interface EvaluationRequest {
  problem: Problem;
  conversation_history: Message[];
  student_answer: string;
  hints_used_so_far: number;
}

export interface EvaluationResponse {
  response_type: 'correct_final' | 'partial_progress' | 'arithmetic_error' | 'conceptual_error' | 'needs_hint';
  tutor_message: string;
  badge_type: 'partial_progress' | 'hint_given' | 'corrective_feedback';
  show_solution_button: boolean;
  explanation?: string; // Only when solution button clicked
}

export interface SimilarProblemRequest {
  original_problem: Problem;
  difficulty_adjustment?: 'same' | 'easier' | 'harder';
}

export interface SimilarProblemResponse {
  problem: Problem;
  generation_metadata: {
    difficulty_adjustment: string;
    similarity_score: number;
  };
}

export interface DiagnosticRequest {
  conversation_history: Message[];
  problem: Problem;
}

export interface DiagnosticResponse {
  likely_misconception: string;
  suggested_intervention: string;
  confidence: number;
}

// UI State types

export interface ChatState {
  currentProblem: Problem | null;
  messages: Message[];
  hintsUsed: number;
  isProcessing: boolean;
  showSolutionButton: boolean;
  masteryCheckActive: boolean;
  sessionId: string;
}

export interface SummaryData {
  session: Session;
  total_problems: number;
  problems_mastered: number;
  total_hints_used: number;
  average_hints_per_problem: number;
  problem_details: {
    problem: Problem;
    hints_used: number;
    mastered: boolean;
    conversation_length: number;
  }[];
}

export interface PickerFilters {
  class: number;
  chapter?: number;
  complexity?: 'easy' | 'medium' | 'hard';
  source_book?: string;
}
